# Generated by Django 6.0.4 on 2026-04-23 12:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.TextField(blank=True, default='', max_length=5000, null=True)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2026, 4, 23, 12, 25, 22, 723111, tzinfo=datetime.timezone.utc))),
                ('update_time', models.DateTimeField(default=datetime.datetime(2026, 4, 23, 12, 25, 22, 723127, tzinfo=datetime.timezone.utc))),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.character')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userprofile')),
            ],
        ),
    ]
