# Generated by Django 6.0.4 on 2026-04-23 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 23, 12, 26, 17, 40874, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='friend',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 23, 12, 26, 17, 40894, tzinfo=datetime.timezone.utc)),
        ),
    ]
