# Generated by Django 6.0.4 on 2026-05-16 14:32

import web.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_voice_character_voice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(
                default="user/photos/default.png",
                upload_to=web.models.user.photo_upload_to,
            ),
        ),
    ]
